# Generated by Django 4.2.7 on 2023-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_confirmationcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.IntegerField(default=0, verbose_name='subscribers'),
        ),
    ]
