version: "3"

services:

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - '6379:6379'

  celery:
    build: .
    tty: true
    command: celery -A sellinf worker -l INFO
    depends_on:
      - app
      - redis

  app:
    build: .
    tty: true
    command: sh -c "./runserver.sh"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      database:
        condition: service_healthy

volumes:
  pg_data: